packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - core-js

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - prisma
  - unrs-resolver
