/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CrawlerRouteImport } from './routes/crawler'
import { Route as IndexRouteImport } from './routes/index'

const CrawlerRoute = CrawlerRouteImport.update({
  id: '/crawler',
  path: '/crawler',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crawler': typeof CrawlerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crawler': typeof CrawlerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crawler': typeof CrawlerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/crawler'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/crawler'
  id: '__root__' | '/' | '/crawler'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrawlerRoute: typeof CrawlerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/crawler': {
      id: '/crawler'
      path: '/crawler'
      fullPath: '/crawler'
      preLoaderRoute: typeof CrawlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrawlerRoute: CrawlerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
