/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LicenseRouteImport } from './routes/license'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedCrawlerReviewRouteImport } from './routes/_authenticated/crawler/review'
import { Route as AuthenticatedCrawlerInsightsRouteImport } from './routes/_authenticated/crawler/insights'
import { Route as AuthenticatedAdminLicenseManagerRouteImport } from './routes/_authenticated/admin/license-manager'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'

const LicenseRoute = LicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCrawlerReviewRoute =
  AuthenticatedCrawlerReviewRouteImport.update({
    id: '/_authenticated/crawler/review',
    path: '/crawler/review',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCrawlerInsightsRoute =
  AuthenticatedCrawlerInsightsRouteImport.update({
    id: '/_authenticated/crawler/insights',
    path: '/crawler/insights',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminLicenseManagerRoute =
  AuthenticatedAdminLicenseManagerRouteImport.update({
    id: '/_authenticated/admin/license-manager',
    path: '/admin/license-manager',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/_authenticated/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/license': typeof LicenseRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/license-manager': typeof AuthenticatedAdminLicenseManagerRoute
  '/crawler/insights': typeof AuthenticatedCrawlerInsightsRoute
  '/crawler/review': typeof AuthenticatedCrawlerReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/license': typeof LicenseRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/license-manager': typeof AuthenticatedAdminLicenseManagerRoute
  '/crawler/insights': typeof AuthenticatedCrawlerInsightsRoute
  '/crawler/review': typeof AuthenticatedCrawlerReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/license': typeof LicenseRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/license-manager': typeof AuthenticatedAdminLicenseManagerRoute
  '/_authenticated/crawler/insights': typeof AuthenticatedCrawlerInsightsRoute
  '/_authenticated/crawler/review': typeof AuthenticatedCrawlerReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/license'
    | '/admin/dashboard'
    | '/admin/license-manager'
    | '/crawler/insights'
    | '/crawler/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/license'
    | '/admin/dashboard'
    | '/admin/license-manager'
    | '/crawler/insights'
    | '/crawler/review'
  id:
    | '__root__'
    | '/'
    | '/license'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/license-manager'
    | '/_authenticated/crawler/insights'
    | '/_authenticated/crawler/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LicenseRoute: typeof LicenseRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminLicenseManagerRoute: typeof AuthenticatedAdminLicenseManagerRoute
  AuthenticatedCrawlerInsightsRoute: typeof AuthenticatedCrawlerInsightsRoute
  AuthenticatedCrawlerReviewRoute: typeof AuthenticatedCrawlerReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/license': {
      id: '/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/crawler/review': {
      id: '/_authenticated/crawler/review'
      path: '/crawler/review'
      fullPath: '/crawler/review'
      preLoaderRoute: typeof AuthenticatedCrawlerReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/crawler/insights': {
      id: '/_authenticated/crawler/insights'
      path: '/crawler/insights'
      fullPath: '/crawler/insights'
      preLoaderRoute: typeof AuthenticatedCrawlerInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/license-manager': {
      id: '/_authenticated/admin/license-manager'
      path: '/admin/license-manager'
      fullPath: '/admin/license-manager'
      preLoaderRoute: typeof AuthenticatedAdminLicenseManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LicenseRoute: LicenseRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminLicenseManagerRoute: AuthenticatedAdminLicenseManagerRoute,
  AuthenticatedCrawlerInsightsRoute: AuthenticatedCrawlerInsightsRoute,
  AuthenticatedCrawlerReviewRoute: AuthenticatedCrawlerReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
